matches_number: Use long long int for 32bit + _FILE_OFFSET_BITS=64
rhinstaller/isomd5sum pull request #21
Opened 2018-12-16 23:08 UTC by rfinnie

Closes rhinstaller/isomd5sum#20

2018-12-17 16:51 UTC, bcl commented
Thanks for the patch, I'll make sure to take a good look at this this week.

2018-12-17 23:53 UTC, rfinnie commented
Thanks. There might be a better way to do this; I steadfastly refuse to claim I am a C programmer by any means.  Changing supported and fragmentcount to off_t seems like a hack, but does work.  (Is there something that can be passed to GCC to say "pretend *everything* is 64-bit and double longs if necessary"?)

2018-12-20 00:19 UTC, bcl approved these changes
I think this is ok, from what I read long long int is guaranteed to be at least 64 bits on all arches.
I'm not sure it needs to be this big, but it doesn't seem to hurt anything.

2018-12-20 00:19 UTC, bcl commented on libcheckisomd5.c
> +        printf("Fragment count: %Lu\n", info->fragmentcount);
This should be %lu off_t is signed not unsigned.

2021-10-28 18:50 UTC, bcl requested changes
Could you rebase this on master and fix the  %Lu?

2024-04-29 22:58 UTC, closed without merging

2026-03-01 03:56 UTC, rfinnie commented
Oh, I'm very sorry I didn't follow up on this one! I can get that fix done and rebase the branch; can you re-open this please?

2026-03-01 04:00 UTC, rfinnie commented on libcheckisomd5.c
> +        printf("Fragment count: %Lu\n", info->fragmentcount);
Fixed

2026-03-02 19:46 UTC, bcl commented
It won't let me reopen it, you'll need to make a new one.